Repository architectury/architectury-api, pull requests merged in 2021-06, with the labels that each got.

#104 Implement phases for BiomeModifications on Forge
  common/src/main/java/me/shedaniel/architectury/hooks/biome/BiomeHooks.java
  common/src/main/java/me/shedaniel/architectury/hooks/biome/GenerationProperties.java
  common/src/main/java/me/shedaniel/architectury/registry/BiomeModifications.java
  forge/src/main/java/me/shedaniel/architectury/registry/forge/BiomeModificationsImpl.java
Labels: api, enhancement, last call, priority: medium

#109 Entity Event: Animal Tame
  common/src/main/java/dev/architectury/event/events/common/EntityEvent.java
  fabric/src/main/java/dev/architectury/mixin/fabric/HorseTameInvoker.java
  fabric/src/main/java/dev/architectury/mixin/fabric/MixinOcelot.java
  fabric/src/main/java/dev/architectury/mixin/fabric/MixinTamableAnimal.java
  fabric/src/main/resources/architectury.mixins.json
  forge/src/main/java/me/shedaniel/architectury/event/forge/EventHandlerImplCommon.java
  testmod-common/src/main/java/dev/architectury/test/events/DebugEvents.java
Labels: api, last call, new feature, priority: medium

#110 Particle Provider API
  common/src/main/java/me/shedaniel/architectury/registry/ParticleProviderRegistry.java
  fabric/src/main/java/me/shedaniel/architectury/registry/fabric/ParticleProviderRegistryImpl.java
  forge/src/main/java/me/shedaniel/architectury/mixin/forge/ParticleEngineAccessor.java
  forge/src/main/java/me/shedaniel/architectury/registry/forge/ParticleProviderRegistryImpl.java
  forge/src/main/resources/architectury.mixins.json
  testmod-common/src/main/java/me/shedaniel/architectury/test/TestMod.java
  testmod-common/src/main/java/me/shedaniel/architectury/test/particle/TestParticles.java
  testmod-common/src/main/resources/assets/architectury-test/particles/test_particle.json
  testmod-common/src/main/resources/assets/architectury-test/textures/particle/test_particle.png
Labels: api, last call, new feature, priority: medium, testmod
