Repository architectury/architectury-api, pull requests merged in 2021-01, with the labels that each got.

#7 Add ClientScreenInputEvent
  common/src/main/java/me/shedaniel/architectury/event/events/client/ClientScreenInputEvent.java
  common/src/test/java/me/shedaniel/architectury/test/ConsoleMessageSink.java
  common/src/test/java/me/shedaniel/architectury/test/MessageSink.java
  common/src/test/java/me/shedaniel/architectury/test/TestMod.java
  common/src/test/java/me/shedaniel/architectury/test/client/ClientOverlayMessageSink.java
  fabric/src/main/java/me/shedaniel/architectury/impl/fabric/ScreenInputDelegate.java
  fabric/src/main/java/me/shedaniel/architectury/mixin/fabric/client/MixinKeyboardHandler.java
  fabric/src/main/java/me/shedaniel/architectury/mixin/fabric/client/MixinMouseHandler.java
  fabric/src/main/java/me/shedaniel/architectury/mixin/fabric/client/MixinScreen.java
  fabric/src/main/resources/architectury.mixins.json
  forge/src/main/java/me/shedaniel/architectury/event/forge/EventHandlerImplClient.java
Labels: enhancement

#10 ArchitecturyBlockEntity to sync data to client
  common/src/main/java/me/shedaniel/architectury/extensions/BlockEntityExtension.java
  common/src/main/java/me/shedaniel/architectury/hooks/BlockEntityHooks.java
  fabric/src/main/java/me/shedaniel/architectury/hooks/fabric/BlockEntityHooksImpl.java
  fabric/src/main/java/me/shedaniel/architectury/mixin/fabric/MixinBlockEntityExtension.java
  fabric/src/main/resources/architectury.mixins.json
  forge/src/main/java/me/shedaniel/architectury/hooks/forge/BlockEntityHooksImpl.java
  forge/src/main/java/me/shedaniel/architectury/mixin/forge/MixinBlockEntity.java
  forge/src/main/java/me/shedaniel/architectury/mixin/forge/MixinBlockEntityExtension.java
  forge/src/main/resources/architectury.mixins.json
Labels: enhancement

#13 Add AbstractRecipeSerializer
  common/src/main/java/me/shedaniel/architectury/core/AbstractRecipeSerializer.java
  forge/src/main/java/me/shedaniel/architectury/mixin/forge/MixinAbstractRecipeSerializer.java
  forge/src/main/java/me/shedaniel/architectury/plugin/forge/ArchitecturyMixinPlugin.java
  forge/src/main/resources/architectury.mixins.json
Labels: enhancement

#20 Add raw input events
  common/src/main/java/me/shedaniel/architectury/event/events/client/ClientRawInputEvent.java
  fabric/build.gradle
  fabric/src/main/java/me/shedaniel/architectury/mixin/fabric/client/MixinKeyboardHandler.java
  fabric/src/main/java/me/shedaniel/architectury/mixin/fabric/client/MixinMouseHandler.java
  forge/src/main/java/me/shedaniel/architectury/event/forge/EventHandlerImplClient.java
  testmod-common/src/main/java/me/shedaniel/architectury/test/TestMod.java
  testmod-common/src/main/java/me/shedaniel/architectury/test/events/DebugEvents.java
Labels: enhancement, testmod

#26 FluidStackHooks in getting the rendering information for the fluids
  common/src/main/java/me/shedaniel/architectury/hooks/FluidStackHooks.java
  fabric/src/main/java/me/shedaniel/architectury/hooks/fabric/FluidStackHooksImpl.java
  forge/src/main/java/me/shedaniel/architectury/hooks/forge/FluidStackHooksImpl.java
Labels: enhancement

#29 Fix mojank stripping containsKey from Registries on Server
  fabric/src/main/java/me/shedaniel/architectury/registry/fabric/RegistriesImpl.java
  forge/src/main/java/me/shedaniel/architectury/registry/forge/RegistriesImpl.java
Labels: bug

#22 Add GuiEvent.SET_SCREEN
  common/src/main/java/me/shedaniel/architectury/event/events/GuiEvent.java
  fabric/src/main/java/me/shedaniel/architectury/mixin/fabric/client/MixinMinecraft.java
  fabric/src/main/resources/architectury.mixins.json
  forge/src/main/java/me/shedaniel/architectury/event/forge/EventHandlerImplClient.java
  testmod-common/src/main/java/me/shedaniel/architectury/test/events/DebugEvents.java
Labels: enhancement
