Repository architectury/architectury-api, pull requests merged in 2021-12, with the labels that each got.

#146 Migrate to transitive access wideners
  build.gradle
  common/build.gradle
  common/src/main/java/dev/architectury/hooks/LevelResourceHooks.java
  common/src/main/java/dev/architectury/hooks/block/BlockEntityHooks.java
  common/src/main/java/dev/architectury/hooks/level/ExplosionHooks.java
  common/src/main/java/dev/architectury/hooks/level/entity/EntityHooks.java
  common/src/main/java/dev/architectury/hooks/level/entity/PlayerHooks.java
  common/src/main/resources/architectury-common.accessWidener
  common/src/main/resources/architectury.common.json
  fabric/build.gradle
  fabric/src/main/java/dev/architectury/hooks/level/entity/fabric/EntityHooksImpl.java
  fabric/src/main/java/dev/architectury/hooks/level/entity/fabric/PlayerHooksImpl.java
  fabric/src/main/java/dev/architectury/hooks/level/fabric/ExplosionHooksImpl.java
  fabric/src/main/java/dev/architectury/mixin/fabric/MixinExplosion.java
  fabric/src/main/resources/architectury.accessWidener
  forge/build.gradle
  forge/src/main/java/dev/architectury/hooks/level/entity/forge/EntityHooksImpl.java
  forge/src/main/java/dev/architectury/hooks/level/entity/forge/PlayerHooksImpl.java
  forge/src/main/java/dev/architectury/hooks/level/forge/ExplosionHooksImpl.java
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  testmod-common/build.gradle
  testmod-fabric/build.gradle
  testmod-forge/build.gradle
Labels: enhancement, last call, api, new feature, priority: medium

#144 Remove hacks around RegistryEntry
  common/src/main/java/dev/architectury/core/RegistryEntry.java
  forge/src/main/java/dev/architectury/mixin/forge/MixinRegistryEntry.java
  forge/src/main/java/dev/architectury/plugin/forge/ArchitecturyMixinPlugin.java
  forge/src/main/resources/architectury.mixins.json
  testmod-common/src/main/java/dev/architectury/test/recipes/TestRecipeSerializer.java
  testmod-common/src/main/java/dev/architectury/test/registry/TestRegistries.java
Labels: enhancement, needs testing, last call, testmod, priority: medium

#149 Add ClientReloadShadersEvent
  common/src/main/java/dev/architectury/event/events/client/ClientReloadShadersEvent.java
  fabric/src/main/java/dev/architectury/mixin/fabric/client/MixinGameRenderer.java
  forge/src/main/java/dev/architectury/event/forge/EventHandlerImplClient.java
  gradle.properties
Labels: last call, api, new feature, priority: medium

#155 Add AWs for RenderType
  common/src/main/resources/architectury-common.accessWidener
  fabric/src/main/resources/architectury.accessWidener
Labels: enhancement, last call, priority: high

#154 @Redirect workaround for closing #152
  fabric/src/main/java/dev/architectury/impl/fabric/ScreenInputDelegate.java
  fabric/src/main/java/dev/architectury/mixin/fabric/client/MixinMouseHandler.java
Labels: help wanted, bug, last call, priority: high

#172 Fix mixin remapping quirk
  fabric/src/main/java/dev/architectury/mixin/fabric/client/MixinMouseHandler.java
Labels: bug, priority: high

#160 Introduce EntitySpawnExtension
  common/src/main/java/dev/architectury/extensions/network/EntitySpawnExtension.java
  common/src/main/java/dev/architectury/networking/NetworkManager.java
  fabric/src/main/java/dev/architectury/networking/fabric/SpawnEntityPacket.java
  forge/src/main/java/dev/architectury/mixin/forge/MixinEntitySpawnExtension.java
  forge/src/main/resources/architectury.mixins.json
Labels: needs testing, last call, api, new feature, priority: medium
