Repository architectury/architectury-api, pull requests merged in 2022-03, with the labels that each got.

#216 Big clean up, more details in the PR
  common/build.gradle
  common/src/main/java/dev/architectury/core/item/ArchitecturySpawnEggItem.java
  common/src/main/java/dev/architectury/event/EventFactory.java
  common/src/main/java/dev/architectury/platform/Platform.java
  common/src/main/java/dev/architectury/registry/block/BlockProperties.java
  common/src/main/java/dev/architectury/registry/block/BlockPropertiesExtension.java
  common/src/main/java/dev/architectury/registry/level/GameRuleFactory.java
  common/src/main/java/dev/architectury/registry/level/GameRuleRegistry.java
  common/src/main/java/dev/architectury/registry/level/advancement/CriteriaTriggersRegistry.java
  common/src/main/java/dev/architectury/registry/level/entity/EntityAttributeRegistry.java
  common/src/main/java/dev/architectury/registry/registries/DeferredRegister.java
  common/src/main/java/dev/architectury/registry/registries/Registrar.java
  common/src/main/java/dev/architectury/registry/registries/RegistrySupplier.java
  common/src/main/resources/architectury-common.accessWidener
  common/src/main/resources/architectury.accessWidener
  common/src/main/resources/architectury.common.json
  fabric/build.gradle
  fabric/src/main/java/dev/architectury/hooks/fluid/fabric/FluidStackHooksImpl.java
  fabric/src/main/java/dev/architectury/platform/fabric/PlatformImpl.java
  fabric/src/main/java/dev/architectury/registry/block/fabric/BlockPropertiesImpl.java
  fabric/src/main/java/dev/architectury/registry/item/fabric/ItemPropertiesRegistryImpl.java
  fabric/src/main/java/dev/architectury/registry/level/advancement/fabric/CriteriaTriggersRegistryImpl.java
  fabric/src/main/java/dev/architectury/registry/level/biome/fabric/BiomeModificationsImpl.java
  fabric/src/main/java/dev/architectury/registry/level/entity/fabric/EntityAttributeRegistryImpl.java
  fabric/src/main/java/dev/architectury/registry/level/fabric/GameRuleFactoryImpl.java
  fabric/src/main/java/dev/architectury/registry/level/fabric/GameRuleRegistryImpl.java
  fabric/src/main/java/dev/architectury/registry/registries/fabric/RegistriesImpl.java
  fabric/src/main/resources/architectury.accessWidener
  fabric/src/main/resources/fabric.mod.json
  forge/build.gradle
  forge/src/main/java/dev/architectury/hooks/fluid/forge/FluidStackHooksImpl.java
  forge/src/main/java/dev/architectury/platform/forge/PlatformImpl.java
  forge/src/main/java/dev/architectury/registry/block/forge/BlockPropertiesImpl.java
  forge/src/main/java/dev/architectury/registry/level/advancement/forge/CriteriaTriggersRegistryImpl.java
  forge/src/main/java/dev/architectury/registry/level/biome/forge/BiomeModificationsImpl.java
  forge/src/main/java/dev/architectury/registry/level/entity/forge/EntityAttributeRegistryImpl.java
  forge/src/main/java/dev/architectury/registry/level/forge/GameRuleFactoryImpl.java
  forge/src/main/java/dev/architectury/registry/level/forge/GameRuleRegistryImpl.java
  forge/src/main/java/dev/architectury/registry/registries/forge/RegistriesImpl.java
  forge/src/main/resources/META-INF/accesstransformer.cfg
  gradle.properties
  testmod-common/src/main/java/dev/architectury/test/TestMod.java
  testmod-common/src/main/java/dev/architectury/test/entity/TestEntity.java
  testmod-common/src/main/java/dev/architectury/test/events/DebugEvents.java
  testmod-common/src/main/java/dev/architectury/test/registry/TestRegistries.java
  testmod-common/src/main/resources/assets/architectury_test/models/item/test_spawn_egg.json
  testmod-fabric/build.gradle
  testmod-forge/build.gradle
Labels: enhancement, last call, priority: medium, 1.18

#222 Update to 22w11a
  common/src/main/java/dev/architectury/hooks/level/biome/BiomeHooks.java
  common/src/main/java/dev/architectury/hooks/level/biome/BiomeProperties.java
  common/src/main/resources/architectury.accessWidener
  fabric/src/main/java/dev/architectury/mixin/fabric/MixinChunkSerializer.java
  fabric/src/main/java/dev/architectury/mixin/fabric/client/MixinScreen.java
  fabric/src/main/java/dev/architectury/registry/level/biome/fabric/BiomeModificationsImpl.java
  fabric/src/main/resources/fabric.mod.json
  gradle.properties
  settings.gradle
Labels: enhancement, priority: high, small change

#220 Fixed EntitySpawnExtension buffer being unable to be read from, #208
  fabric/src/main/java/dev/architectury/networking/fabric/SpawnEntityPacket.java
Labels: bug, priority: high, small change

#228 Fix RegistrySupplier#listen and ArchitecturySpawnEggItem
  common/src/main/java/dev/architectury/core/item/ArchitecturySpawnEggItem.java
  common/src/main/java/dev/architectury/registry/client/level/entity/EntityRendererRegistry.java
  fabric/src/main/java/dev/architectury/registry/client/level/entity/fabric/EntityRendererRegistryImpl.java
  fabric/src/main/java/dev/architectury/registry/registries/fabric/RegistriesImpl.java
  forge/src/main/java/dev/architectury/registry/client/level/entity/forge/EntityRendererRegistryImpl.java
  forge/src/main/java/dev/architectury/registry/registries/forge/RegistriesImpl.java
  testmod-common/src/main/java/dev/architectury/test/TestMod.java
  testmod-common/src/main/java/dev/architectury/test/entity/TestEntity.java
  testmod-common/src/main/java/dev/architectury/test/registry/TestRegistries.java
  testmod-common/src/main/resources/assets/architectury_test/models/item/test_spawn_egg_2.json
Labels: bug, testmod, priority: high, small change
