Repository architectury/architectury-api, pull requests merged in 2022-06, with the labels that each got.

#273 Fix SplitPacketTransformer not saving enough space for packet id
  common/src/main/java/dev/architectury/networking/transformers/SplitPacketTransformer.java
Labels: bug, priority: high, small change

#272 Implement hasTag onto BiomeContext
  common/src/main/java/dev/architectury/registry/level/biome/BiomeModifications.java
  fabric/src/main/java/dev/architectury/registry/level/biome/fabric/BiomeModificationsImpl.java
  forge/src/main/java/dev/architectury/registry/level/biome/forge/BiomeModificationsImpl.java
Labels: enhancement, last call, priority: medium, 1.19

#274 Migrate to Unified Publishing
  .github/workflows/1.18_push.yml
  build.gradle
  fabric/build.gradle
  forge/build.gradle
Labels: enhancement, priority: medium, small change

#281 Fix #278
  forge/src/main/java/dev/architectury/event/forge/EventHandlerImplClient.java
  forge/src/main/java/dev/architectury/event/forge/EventHandlerImplCommon.java
Labels: bug, priority: high, Forge, 1.19

#277 Add stack-aware CraftingRemainingItem
  common/src/main/java/dev/architectury/hooks/item/ItemStackHooks.java
  fabric/src/main/java/dev/architectury/hooks/item/fabric/ItemStackHooksImpl.java
  forge/src/main/java/dev/architectury/hooks/item/forge/ItemStackHooksImpl.java
Labels: enhancement, last call, priority: medium

#280 Implement Forge's new Fluid API
  common/src/main/java/dev/architectury/core/fluid/ArchitecturyFluidAttributes.java
  common/src/main/java/dev/architectury/core/fluid/SimpleArchitecturyFluidAttributes.java
  fabric/src/main/java/dev/architectury/core/fluid/fabric/ArchitecturyFluidRenderingFabric.java
  forge/src/main/java/dev/architectury/core/fluid/forge/imitator/ArchitecturyFlowingFluid.java
  forge/src/main/java/dev/architectury/core/fluid/forge/imitator/ArchitecturyFluidAttributesForge.java
  forge/src/main/java/dev/architectury/hooks/fluid/forge/FluidStackHooksImpl.java
  gradle.properties
Labels: enhancement, needs testing, last call, new feature, priority: high, 1.19
