Repository architectury/architectury-api, pull requests merged in 2022-08, with the labels that each got.

#310 Add more validation to NetworkManagerImpl
  fabric/src/main/java/dev/architectury/networking/fabric/NetworkManagerImpl.java
  forge/src/main/java/dev/architectury/networking/forge/NetworkManagerImpl.java
Labels: priority: low, api, 1.18, small change

#257 Add simple interface injection extensions
  common/src/main/java/dev/architectury/core/fluid/SimpleArchitecturyFluidAttributes.java
  common/src/main/java/dev/architectury/core/item/ArchitecturySpawnEggItem.java
  common/src/main/java/dev/architectury/extensions/injected/InjectedBlockExtension.java
  common/src/main/java/dev/architectury/extensions/injected/InjectedBucketItemExtension.java
  common/src/main/java/dev/architectury/extensions/injected/InjectedEntityTypeExtension.java
  common/src/main/java/dev/architectury/extensions/injected/InjectedFluidExtension.java
  common/src/main/java/dev/architectury/extensions/injected/InjectedFoodPropertiesBuilderExtension.java
  common/src/main/java/dev/architectury/extensions/injected/InjectedGameEventExtension.java
  common/src/main/java/dev/architectury/extensions/injected/InjectedItemExtension.java
  common/src/main/java/dev/architectury/extensions/injected/InjectedRegistryEntryExtension.java
  common/src/main/java/dev/architectury/mixin/inject/MixinBlock.java
  common/src/main/java/dev/architectury/mixin/inject/MixinBlockEntityType.java
  common/src/main/java/dev/architectury/mixin/inject/MixinBucketItem.java
  common/src/main/java/dev/architectury/mixin/inject/MixinEntityType.java
  common/src/main/java/dev/architectury/mixin/inject/MixinFluid.java
  common/src/main/java/dev/architectury/mixin/inject/MixinItem.java
  common/src/main/resources/architectury-common.mixins.json
  common/src/main/resources/architectury.common.json
  fabric/src/main/java/dev/architectury/hooks/item/tool/fabric/HoeItemHooksImpl.java
  forge/src/main/java/dev/architectury/hooks/item/tool/forge/HoeItemHooksImpl.java
Labels: enhancement, last call, priority: medium

#325 Prevent running 1.19 Arch API on 1.19.1+
  fabric/src/main/resources/fabric.mod.json
  forge/mods.toml
  forge/src/main/resources/META-INF/mods.toml
Labels: small change, 1.19
