Repository architectury/architectury-api, pull requests merged in 2022-04, with the labels that each got.

#235 Synchronise it properly?
  forge/src/main/java/dev/architectury/event/forge/EventHandlerImpl.java
  forge/src/main/java/dev/architectury/platform/forge/EventBuses.java
Labels: bug, small change

#240 Add container render events
  common/src/main/java/dev/architectury/event/events/client/ClientGuiEvent.java
  fabric/src/main/java/dev/architectury/mixin/fabric/client/MixinAbstractContainerScreen.java
  fabric/src/main/resources/architectury.mixins.json
  forge/src/main/java/dev/architectury/event/forge/EventHandlerImplClient.java
Labels: enhancement, last call, api, priority: medium, 1.18

#244 Make AW for `MenuType$MenuSupplier` transitive, deprecate `MenuRegistry.of`
  common/src/main/java/dev/architectury/registry/menu/MenuRegistry.java
  common/src/main/resources/architectury.accessWidener
Labels: priority: low, api, 1.18, small change

#243 Introduce FluidBucketHooks.getFluid
  common/src/main/java/dev/architectury/hooks/fluid/FluidBucketHooks.java
  fabric/src/main/java/dev/architectury/hooks/fluid/fabric/FluidBucketHooksImpl.java
  fabric/src/main/java/dev/architectury/mixin/fabric/BucketItemAccessor.java
  fabric/src/main/resources/architectury.mixins.json
  forge/src/main/java/dev/architectury/hooks/fluid/forge/FluidBucketHooksImpl.java
Labels: enhancement, last call, priority: low, api
