Repository architectury/architectury-api, pull requests merged in 2022-05, with the labels that each got.

#247 Add more fluid attributes
  build.gradle
  common/src/main/java/dev/architectury/hooks/fluid/FluidStackHooks.java
  fabric/src/main/java/dev/architectury/hooks/fluid/fabric/FluidStackHooksImpl.java
  forge/src/main/java/dev/architectury/hooks/fluid/forge/FluidStackHooksImpl.java
Labels: enhancement, last call, api, priority: medium, 1.18

#250 Add ArchitecturyRecordItem
  common/src/main/java/dev/architectury/core/item/ArchitecturyRecordItem.java
  common/src/main/resources/architectury.accessWidener
Labels: last call, priority: medium, 1.18

#253 Work on fixing issues
  common/src/main/java/dev/architectury/hooks/item/tool/HoeItemHooks.java
  fabric/src/main/java/dev/architectury/hooks/item/tool/fabric/HoeItemHooksImpl.java
  fabric/src/main/java/dev/architectury/registry/registries/fabric/RegistriesImpl.java
  forge/src/main/java/dev/architectury/hooks/item/tool/forge/HoeItemHooksImpl.java
  forge/src/main/java/dev/architectury/registry/registries/forge/RegistriesImpl.java
  gradle.properties
  testmod-common/src/main/java/dev/architectury/test/item/TestBlockInteractions.java
  testmod-common/src/main/java/dev/architectury/test/registry/TestRegistries.java
Labels: bug, testmod, priority: high, small change

#263 Add rudimentary support for modrinth publishing
  .github/workflows/1.18_push.yml
  build.gradle
  fabric/build.gradle
  forge/build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, priority: medium, small change

#268 Further platform extensions
  common/src/main/java/dev/architectury/platform/Mod.java
  fabric/src/main/java/dev/architectury/platform/fabric/PlatformImpl.java
  forge/src/main/java/dev/architectury/platform/forge/PlatformImpl.java
Labels: enhancement, priority: medium, small change

#269 Fix Platform#getFilePath not returning the *root* file path on Forge
  common/src/main/java/dev/architectury/platform/Mod.java
  fabric/src/main/java/dev/architectury/platform/fabric/PlatformImpl.java
  forge/src/main/java/dev/architectury/platform/forge/PlatformImpl.java
Labels: bug, priority: high, small change

#270 Fix split packet transformer splitting into wrong parts, minus 10 mor…
  common/src/main/java/dev/architectury/networking/transformers/SplitPacketTransformer.java
  testmod-common/src/main/java/dev/architectury/test/networking/TestModNet.java
Labels: bug, priority: high, small change
