Repository architectury/architectury-api, pull requests merged in 2022-02, with the labels that each got.

#201 Some cleanup for Platform class and other platform-specific stuff
  common/src/main/java/dev/architectury/platform/Platform.java
  fabric/src/main/java/dev/architectury/platform/fabric/PlatformImpl.java
  forge/src/main/java/dev/architectury/platform/forge/EventBuses.java
  forge/src/main/java/dev/architectury/platform/forge/PlatformImpl.java
Labels: enhancement, last call, priority: low

#193 Allow registering entries after it has been collected on Forge
  forge/src/main/java/dev/architectury/registry/registries/forge/RegistriesImpl.java
Labels: bug, last call, priority: high

#203 Mark OptiFabric as incompatible
  fabric/src/main/resources/fabric.mod.json
Labels: last call, priority: high
